### ISSUE TITLE
alevin-fry doesn't compile with rand 0.8.3.

### ISSUE THREAD

**Issue by detrout** [COMBINE-lab/alevin-fry#17]
Hi I was trying to build alevin-fry and encountered this error.
```
   Compiling alevin-fry v0.1.0 (/home/diane/proj/delaney/alevin-fry)
error[E0061]: this function takes 1 argument but 2 arguments were supplied
  --> src/main.rs:33:27
   |
33 |             let idx = rng.gen_range(0, CHARSET.len());
   |                           ^^^^^^^^^ -  ------------- supplied 2 arguments
   |                           |
   |                           expected 1 argument

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
error: could not compile `alevin-fry`.
```

I looked through the documentation for rng.gen_range and it seems to now want a "range" low..high.
https://docs.rs/rand/0.8.3/rand/trait.Rng.html

**Comment by rob-p** [comment]
Thanks for reporting the issue, @detrout!  Indeed, they changed the interface and the version was not pinned in `cargo.toml`.  The easiest solution, since you are building from source, is to build from the develop branch which updates the call to conform to the new `rng.gen_range` interface.  Alternatively, you can use main but change `cargo.toml` to pin the rand crate at `0.7.3`.

**Comment by rob-p** [comment]
In addition to being fixed on develop, this is now fixed on master within the big update and the 0.2.0 release.  In particular, the `statrs` dependency on rand 0.7.3 was reported and fixed upstream, so now rand is constrained at ^0.8.3, and works with the version of `statrs` we are pulling.

**Comment by detrout** [comment]
Thanks for fixing it!
