### ISSUE TITLE
Installation via cargo failing, issue with mimalloc/stdatomic

### ISSUE THREAD

**Issue by jeremymsimon** [COMBINE-lab/alevin-fry#39]
This very well could be environment specific, but installation of `alevin-fry` via `Cargo` on our compute node is failing with the following errors/warnings:

```
$ cargo install alevin-fry

The following warnings were emitted during compilation:

warning: In file included from c_src/mimalloc/include/mimalloc-types.h:13:0,
warning:                  from c_src/mimalloc/include/mimalloc-internal.h:11,
warning:                  from c_src/mimalloc/src/static.c:17:
warning: c_src/mimalloc/include/mimalloc-atomic.h:34:23: fatal error: stdatomic.h: No such file or directory
warning:  #include <stdatomic.h>
warning:                        ^
warning: compilation terminated.

error: failed to run custom build command for `libmimalloc-sys v0.1.23`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install1XEavd/release/build/libmimalloc-sys-48dc093a1c32b9e6/build-script-build` (exit status: 1)
```
```
error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_DEBUG=0" "-o" "/tmp/cargo-install1XEavd/release/build/libmimalloc-sys-4cb97a8c24518d43/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c" with args "cc" did not execute successfully (status code exit status: 1).
```

Happy to reach out to our computing folks if it's something system-side that needs to be addressed!

**Comment by jeremymsimon** [comment]
I believe I was trying this with gcc 6.3.0 loaded as a module, but I have some newer versions available too (9.1.0, 11.2.0) that I could try if you think that would get around it. Do I need to specify an explicit path either to cargo or as an environmental variable to make sure it's loading the correct one? Because simply loading those and doing `cargo install alevin-fry` again produces the same error regardless of the version

**Comment by rob-p** [comment]
Hi @jeremymsimon,

  I can confirm that it fails for me with 6.2.0, but works with 9.3.0 and 9.4.0 (don't have 11 to try).  I *think* the compiler used by default depends on what it finds.  The differences in my case (these are both on the same machine) is that `which c++` resolves to the correct c++ compiler and `which cc` resolves to the correct c compiler.

--Rob

**Comment by jeremymsimon** [comment]
@rob-p Hmm okay. So I know virtually nothing about how this all works under the hood, but here's what I have:

```
$ module load gcc/9.1.0 
$ which gcc
/nas/longleaf/apps/gcc/9.1.0/bin/gcc
$ gcc --version
gcc (GCC) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ which cc
/usr/bin/cc
$ cc --version
cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ which c++
/nas/longleaf/apps/gcc/9.1.0/bin/c++
$ c++ --version
c++ (GCC) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

We don't have a `cc` module available, so that seems to be an older version. I could try to manually install an update on that if you think it's needed. Note that with `gcc` v9.1 loaded the original error still persists

**Comment by rob-p** [comment]
@jeremymsimon,

  So that's interesting. `cc` is the default name for the `C` compiler `c++` is for the C++ compiler (unsurprisingly).  The problem is that `gcc`, while being a C compiler, is very compiler specific (e.g. should Clang declare a `gcc` executable? Actually, Apple did this, but that's beside the point).  All you need for `cc` to pick up the right thing, I believe, is to have a binary called `cc` in your path ahead of `/usr/bin/cc`.  One simply hack would be to make a symlink to `/nas/longleaf/apps/gcc/9.1.0/bin/gcc`, and put the location of that symlink at the head of your `PATH` variable.  that might work?

--Rob

**Comment by rob-p** [comment]
This was eventually resolved by ensuring the build environment had access to a modern `cc`, and `c++` executable, as well as a modern version of `CMake` (which mimalloc relies upon for building).  Thanks for the bug report @jeremymsimon!
